sudo: false
language: erlang
otp_release:
       - R15B03
       - R16B03-1
       - 17.5
       - 18.0
       - 18.1
       - 19.2

before_script: "make depss"
script: "make test"
branches:
        only:
            - master
